### ISSUE TITLE
构建微信小游戏还要配置什么才能运行起来？

### ISSUE THREAD

**Issue by rockyxia** [Gifan/killMonster#2]
我目前构建完在小程序开发工具中开通了云开发，还需要配置什么才能运行起来啊

目前是两处报错

一、
VM1341:1 MiniProgramError
module "subdominesub.js" is not defined
Error: module "subdominesub.js" is not defined
    at require (http://127.0.0.1:62316/game/__dev__/WAGameSubContext.js:2:87035)
    at <anonymous>:1:51
    at doWhenAllScriptLoaded (http://127.0.0.1:62316/game/__context__/subContext.js:20:23)
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:62316/game/__context__/subContext.js:31:7)
    at HTMLScriptElement.script.onload (http://127.0.0.1:62316/game/__context__/subContext.js:40:22)

二、
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api; 
    at new u (VM1350 WAGame.js:2)
    at f (VM1350 WAGame.js:2)
    at d (VM1350 WAGame.js:2)
    at Function.success (VM1350 WAGame.js:2)
    at h (VM1350 WAGame.js:2)
    at VM1350 WAGame.js:2
    at C (VM1350 WAGame.js:2)
    at Function.<anonymous> (VM1350 WAGame.js:2)
    at h (VM1350 WAGame.js:2)
    at VM1350 WAGame.js:2

**Comment by rockyxia** [comment]
找到了，在配置文件中修改云开发环境的名称

**Comment by rockyxia** [comment]
但是发现构建的包达到了5.7m

**Comment by rockyxia** [comment]
res资源从服务器加载解决了，感谢
